export const types={
    authChecking:'[auth] Checking login state',
    authCheckingFinish:'[auth] Finish checking login state',
    authStartLogin:'[auth] Start login',
    authLogin:'[auth] Login',
    authRegister:'[auth] Start Register',
    authStartTokenRenew:'[auth] Start Token Renew',
    authLogout:'[auth] Logout',
    
    dataLoaded:'[vacancies] data Loaded',
    vacanciesStartLoading:'[vacancies] Start Loading Vacancies',
    vacanciesLoaded:'[vacancies] Vacancies Loaded',
    vacanciesNextLoading:'[vacancies] Next Loading Vacancies',
    vacancieLoading:'[vacancies] Start loading Vacancies',
    vancieLoaded:'[vacancies] Vacancie Loaded',
    vacanciePremiumLoaded:'[vacancies] Vacancie premium Loaded',
    vacanciesBestLoaded:'[vacancies] Best vacancies loaded',
    vacancieDataChart:'[vacancies] Data Chart',

    adminUsersReports:'[admin] Reported Users',
    adminVacanciesReports:'[admin] Reports Vacancies',
    adminRequests:'[admin] Requests ATKnow',
    adminNextReports:'[admin] Next Reports',
    adminReportLoaded:'[admin] Report Loaded',
    adminDataLoaded:'[admin] Data Loaded',
}  